theme: jekyll-theme-cayman
title: Fluxtion service starter
description: Documentation for Fluxtion service starter
remote_theme: pmarsceill/just-the-docs
aux_links:
  "release 0.1.16":
    - "//github.com/gregv12/fluxtion-service-starter/tree/v0.1.16"
heading_anchors: true

compress_html:
  ignore:
    envs: all

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

logo: "/images/fluxtion_logo_small.png"
