name: Testing github actions

on:
  push:
    branches:
      - release_test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: merge to master and develop
        run: |
          echo pushing branches and tags
          git checkout master 
          git merge release_test
          git checkout develop 
          git merge release_test
          echo pushed branches and tags
