name: Testing github merging

on:
  push:
    branches:
      - release_test

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge release -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: master
          github_token: ${{ github.token }}

      - name: Merge release -> development
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: master
          target_branch: develop
          github_token: ${{ github.token }}